version: "3.4"
services:
  app:
    build:
      context: .
    working_dir: /web/html/
    volumes:
      - $PWD/src/:/web/html/
      - $PWD/resources/certs:/etc/nginx/certs
      - $PWD/resources/secrets:/run/secrets
    env_file: $PWD/src/.env
    container_name: lan_manager_app
    networks:
      - lan
    ports:
      - 80:80
      - 443:443
  database:
    image: mysql:5.6
    volumes:
      - lan_manager_database:/var/lib/mysql
    env_file: $PWD/src/.env
    ports:
      - 3306:3306
    container_name: lan_manager_database
    networks:
      - lan
volumes:
  lan_manager_database:
    name: lan_manager_database
networks:
  lan:
    external: true