version: '2'
services:
  app:
    build:
      context: ./docker/app
      dockerfile: app.dockerfile
    working_dir: /var/www
    container_name: lanops_web_app
    volumes:
      - .:/var/www
    env_file: .env
  server:
    build:
      context: ./docker/server
      dockerfile: server.dockerfile
    working_dir: /var/www
    container_name: lanops_web_server
    volumes:
      - ./certs:/etc/nginx/certs
    volumes_from:
      - app
    env_file: .env
    ports:
      - 80:80
      - 443:443
  database:
    build:
      context: ./docker/db
      dockerfile: db.dockerfile
    volumes:
      - lanops_db:/var/lib/mysql
    container_name: lanops_web_database
    env_file: .env
    ports:
        - "3306:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - database
    container_name: lanops_web_phpmyadmin
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
    ports:
      - '8081:80'
volumes:
  lanops_db: