---
kind: pipeline
name: default

steps:
- name: notify-discord-start
  image: plugins/webhook
  settings:
    urls: 
      from_secret: DISCORD_WEBHOOK_URL
    template: |
      {
        "content": "Starting build"
      }
- name: build-structure
  image: alpine:3.8
  commands:
  - apk add make
  - make folder-structure layout-images env-file
  when:
    event:
    - push
    
- name: build-composer
  image: composer
  commands:
  - cd src/
  - composer install --ignore-platform-reqs --no-scripts
  when:
    event:
    - push
    
- name: build-npm
  image: node:8
  commands:
  - cd src/
  - npm install && node_modules/.bin/gulp --production
  when:
    event:
    - push
    
- name: build-image  
  image: plugins/docker
  settings:
    repo: lanopsdev/manager
    tags: latest
    dry_run: true
  when:
    event:
    - push
    
- name: test-phpunit
  image: lanopsdev/manager:latest
  environment:
    APP_KEY:
      from_secret: TEST_APP_KEY
  commands:
  - cd /web/html/
  - ls
  - php artisan migrate --force
  - php artisan db:seed --force
  - vendor/bin/phpunit
  when:
    event:
    - push
    
- name: push-image
  image: plugins/docker
  settings:
    repo: lanopsdev/manager
    tags: latest
    username:
      from_secret: DOCKERHUB_USERNAME
    password:
      from_secret: DOCKERHUB_PASSWORD
  when:
    event:
    - tag
    branch:
    - master

- name: notify-discord
  image: plugins/webhook
  settings:
    urls: 
      from_secret: DISCORD_WEBHOOK_URL
    template: |
      {
        "content": "{{ build.status }}"
      }
  # image: appleboy/drone-discord
  # settings:
  #   webhook_id:
  #     from_secret: DISCORD_WEBHOOK_ID
  #   webhook_token:
  #     from_secret: DISCORD_WEBHOOK_TOKEN
  #   message: |
  #     {{ #success build.status }}
  #       build {{ build.number }} succeeded. Good job.
  #     {{ else }}
  #       build {{ build.number }} failed. Fix me please.
  #     {{ /success }}
  when:
    event:
    - push

trigger:
  branch:
  - master
  - staging
  - feat/*

services:
- name: database
  image: mysql:5.6
  environment:
    MYSQL_DATABASE: lan_manager
    MYSQL_USER: lan_manager
    MYSQL_PASSWORD: password
    MYSQL_RANDOM_ROOT_PASSWORD: true
---
kind: signature
hmac: baf8a340a0e891777f4c86327464317adb90ba253c9a5b15adcf80e74474e17d

...
