kind: pipeline
name: default

steps:
- name: test
  image: docker:dind
  privileged: true
  commands:
  - apk add make
  - make app-build-docker
  - docker run -d lanopsdev/manager:ci-test
  - make database-migrate database-seed generate-key
  - make stop
  when:
    event:
    - push
services:
- name: database
  image: mysql:5.6
  environment:
    MYSQL_DATABASE: lan_manager
    MYSQL_USER: lan_manager
    MYSQL_PASSWORD: password
    MYSQL_RANDOM_ROOT_PASSWORD: true