kind: pipeline
name: default

steps:
- name: build-composer
  image: composer
  commands:
  - cd src/
  - composer install --ignore-platform-reqs --no-scripts
  when:
    event:
    - push
- name: build-npm
  image: node:8
  commands:
  - cd src/
  - npm install && node_modules/.bin/gulp --production
  when:
    event:
    - push
- name: build-structure
  image: alpine:3.8
  commands:
  - apk add make
  - make folder-structure layout-images env-file
  when:
    event:
    - push
- name: build-image  
  image: plugins/docker
  settings:
    repo: lanopsdev/manager
    tags: ci-test
    dry_run: true
  when:
    event:
    - push
- name: test-image
  image: lanopsdev/manager:ci-test
  commands:
  - ls
  - cd /web/html/
  - ls
  - cat .env
  - php -v
  - php artisan key:generate
  - php artisan migrate --force
  - php artisan db:seed --force
  when:
    event:
    - push
services:
- name: database
  image: mysql:5.6
  environment:
    MYSQL_DATABASE: lan_manager
    MYSQL_USER: lan_manager
    MYSQL_PASSWORD: password
    MYSQL_RANDOM_ROOT_PASSWORD: true